# Generated by Django 5.0.9 on 2026-01-15 21:48

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiGateDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('default_vdom', models.CharField(default='root', max_length=64)),
                ('api_port', models.PositiveIntegerField(default=443)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('fortios_version', models.CharField(blank=True, max_length=32)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fortigate', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'FortiGate device',
                'verbose_name_plural': 'FortiGate devices',
                'ordering': ('device__name',),
            },
        ),
    ]
