# Generated by Django 5.2.10 on 2026-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='destination_interface',
            field=models.ManyToManyField(limit_choices_to={'is_decommissioned': False, 'type__in': ['zone', 'interface']}, related_name='%(class)s_dst_object', to='netbox_fortigate.object'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='service',
            field=models.ManyToManyField(limit_choices_to={'is_decommissioned': False, 'type__in': ['service', 'service group']}, related_name='%(class)s_service', to='netbox_fortigate.object'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='source_interface',
            field=models.ManyToManyField(limit_choices_to={'is_decommissioned': False, 'type__in': ['zone', 'interface']}, related_name='%(class)s_src_object', to='netbox_fortigate.object'),
        ),
    ]
