# Generated by Django 5.0.9 on 2026-01-15 22:00

import netbox_fortigate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortigatedevice',
            name='verify_ssl',
        ),
        migrations.AlterField(
            model_name='fortigatedevice',
            name='api_port',
            field=models.PositiveIntegerField(default=443),
        ),
        migrations.AlterField(
            model_name='fortigatedevice',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
    ]
