# Generated by Django 5.2.10 on 2026-02-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0002_alter_policy_destination_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='fortigate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='netbox_fortigate.fortigate'),
        ),
    ]
