# Generated by Django 5.0.9 on 2026-01-15 23:12

import django.db.models.deletion
import ipam.fields
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_fortigate', '0002_remove_fortigatedevice_verify_ssl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortigatedevice',
            name='fortios_version',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='fortigatedevice',
            name='role',
            field=models.CharField(default='firewall', max_length=64),
        ),
        migrations.CreateModel(
            name='FortiGateInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('ip', ipam.fields.IPAddressField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(blank=True, default='', max_length=32)),
                ('vdom', models.CharField(default='root', max_length=64)),
                ('status', models.CharField(default='down', max_length=8)),
                ('fortigate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='netbox_fortigate.fortigatedevice')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_interfaces', to='netbox_fortigate.fortigateinterface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('fortigate__device__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FortiGateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=35)),
                ('type', models.CharField(default='normal', max_length=16)),
                ('intrazone', models.CharField(default='deny', max_length=8)),
                ('fortigate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='netbox_fortigate.fortigatedevice')),
                ('interface', models.ManyToManyField(blank=True, related_name='zones', to='netbox_fortigate.fortigateinterface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('fortigate__device__name', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='fortigateinterface',
            constraint=models.UniqueConstraint(fields=('fortigate', 'name'), name='uniq_fg_if_name'),
        ),
        migrations.AddConstraint(
            model_name='fortigatezone',
            constraint=models.UniqueConstraint(fields=('fortigate', 'name'), name='uniq_fg_zone_name'),
        ),
    ]
