# Generated by Django 5.0.9 on 2026-01-15 23:54

import django.db.models.deletion
import ipam.fields
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_fortigate', '0003_alter_fortigatedevice_fortios_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiGateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('route', ipam.fields.IPNetworkField()),
                ('version', models.SmallIntegerField(default=4)),
                ('type', models.CharField(default='connect', max_length=64)),
                ('gateway', ipam.fields.IPAddressField(blank=True, null=True)),
                ('distance', models.SmallIntegerField(default=0)),
                ('priority', models.SmallIntegerField(default=0)),
                ('metric', models.SmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('fortigate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='netbox_fortigate.fortigatedevice')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='netbox_fortigate.fortigateinterface')),
                ('next_hop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_hop_routes', to='netbox_fortigate.fortigatedevice')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'routing table',
                'verbose_name_plural': 'routing table',
                'ordering': ('-route', 'distance', 'metric'),
            },
        ),
        migrations.AddConstraint(
            model_name='fortigateroute',
            constraint=models.UniqueConstraint(fields=('fortigate', 'route', 'interface', 'enabled'), name='uniq_fg_route_per_interface_enabled'),
        ),
        migrations.AddConstraint(
            model_name='fortigateroute',
            constraint=models.UniqueConstraint(fields=('fortigate', 'route', 'interface', 'gateway', 'enabled'), name='uniq_fg_route_gateway_per_interface_enabled'),
        ),
    ]
