# Generated by Django 5.2.10 on 2026-03-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0003_alter_interfaces_fortigate'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_decommissioned',
            field=models.BooleanField(default=False),
        ),
    ]
