# Generated by Django 5.0.9 on 2026-01-27 19:23

import django.db.models.deletion
import netbox_fortigate.models.devices
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_fortigate', '0004_fortigateroute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortigatedevice',
            name='api_port',
            field=models.PositiveIntegerField(default=netbox_fortigate.models.devices.default_api_port),
        ),
        migrations.AlterField(
            model_name='fortigatedevice',
            name='ssh_port',
            field=models.PositiveIntegerField(default=netbox_fortigate.models.devices.default_ssh_port),
        ),
        migrations.CreateModel(
            name='FortiGateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('fortigate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fortigate_objects', to='netbox_fortigate.fortigatedevice')),
                ('object_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'netbox_fortigate'), ('model', 'fortigateinterface')), models.Q(('app_label', 'netbox_fortigate'), ('model', 'fortigatezone')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'FortiGate Object',
                'verbose_name_plural': 'FortiGate Objects',
                'ordering': ('fortigate__device__name', 'type', 'name', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='fortigateobject',
            constraint=models.UniqueConstraint(fields=('fortigate', 'object_type', 'object_id'), name='uniq_fortigate_object_target'),
        ),
    ]
