# Generated by Django 5.2.10 on 2026-03-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0004_object_is_decommissioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='poolname',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='ip_pool',
        ),
        migrations.DeleteModel(
            name='IPPool',
        ),
    ]
