# Generated by Django 5.0.9 on 2026-01-27 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_fortigate', '0005_alter_fortigatedevice_api_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortigatedevice',
            name='mgmt_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
    ]
