# Generated by Django 5.0.9 on 2026-01-28 18:40

import datetime
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_fortigate', '0006_fortigatedevice_mgmt_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiGateScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='daily', max_length=10)),
                ('time_of_day', models.TimeField(default=datetime.time(1, 0))),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
