# Generated by Django 5.0.9 on 2026-01-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_fortigate', '0007_fortigatescheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortigatescheduler',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fortigatescheduler',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fortigatescheduler',
            name='interval_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fortigatescheduler',
            name='job_type',
            field=models.CharField(default='inventory_pull', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fortigatescheduler',
            name='schedule_mode',
            field=models.CharField(default='cron', max_length=32),
        ),
        migrations.AlterField(
            model_name='fortigatescheduler',
            name='frequency',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='fortigatescheduler',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='fortigatescheduler',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_mode', 'interval')), fields=('job_type', 'interval_minutes'), name='uniq_fgt_sched_interval_jobtype_minutes'),
        ),
        migrations.AddConstraint(
            model_name='fortigatescheduler',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_mode', 'cron')), fields=('job_type', 'frequency', 'time_of_day', 'weekday', 'day_of_month'), name='uniq_fgt_sched_cron_jobtype_when'),
        ),
    ]
