# Generated by Django 5.0.9 on 2026-01-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0008_fortigatescheduler_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortigatescheduler',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
