# Generated by Django 5.2.10 on 2026-02-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fortigate', '0010_fortigatedevice_owner_fortigateinterface_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortigateinterface',
            name='is_decommissioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fortigatezone',
            name='is_decommissioned',
            field=models.BooleanField(default=False),
        ),
    ]
